import { Sparkles } from 'lucide-react';

interface OverviewProps {
  confidence: number;
  structuralRegime: string;
}

export default function Overview({ confidence, structuralRegime }: OverviewProps) {
  return (
    <div className="bg-gradient-to-br from-slate-800 to-slate-900 rounded-xl p-8 border border-cyan-500/20 shadow-xl">
      <div className="flex items-center gap-3 mb-4">
        <Sparkles className="text-cyan-400" size={32} />
        <h1 className="text-3xl font-bold text-slate-100">
          Quantum-Morph Material Design Result
        </h1>
      </div>

      <p className="text-slate-300 mb-6 leading-relaxed">
        This result was generated by an AI-driven optimization engine that designs
        carbon capture materials from waste. The system analyzes multiple parameters
        to create optimal composite materials for CO₂ adsorption.
      </p>

      <div className="grid md:grid-cols-2 gap-6">
        <div>
          <label className="text-sm text-slate-400 mb-2 block">Model Confidence</label>
          <div className="relative h-8 bg-slate-700 rounded-full overflow-hidden">
            <div
              className="absolute h-full bg-gradient-to-r from-cyan-500 to-teal-400 transition-all duration-1000 ease-out flex items-center justify-end pr-3"
              style={{ width: `${confidence}%` }}
            >
              <span className="text-sm font-semibold text-slate-900">{confidence}%</span>
            </div>
          </div>
        </div>

        <div>
          <label className="text-sm text-slate-400 mb-2 block">Structural Regime</label>
          <div className="h-8 flex items-center">
            <span className="px-4 py-1 bg-teal-500/20 text-teal-300 rounded-full text-sm font-medium border border-teal-500/30">
              {structuralRegime}
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
