import { useState } from 'react';
import { QuantumMorphResult } from './types/QuantumMorph';
import { sampleData } from './utils/sampleData';
import Overview from './components/Overview';
import MaterialInput from './components/MaterialInput';
import ProcessPipeline from './components/ProcessPipeline';
import CompositeFormation from './components/CompositeFormation';
import Performance from './components/Performance';
import RiskAssessment from './components/RiskAssessment';
import ScientificInterpretation from './components/ScientificInterpretation';
import FileUpload from './components/FileUpload';

function App() {
  const [data, setData] = useState<QuantumMorphResult | null>(null);
  const [showUpload, setShowUpload] = useState(true);

  const handleDataLoaded = (newData: QuantumMorphResult) => {
    setData(newData);
    setShowUpload(false);
  };

  const handleUseSample = () => {
    setData(sampleData);
    setShowUpload(false);
  };

  const handleReset = () => {
    setData(null);
    setShowUpload(true);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950">
      <div className="max-w-6xl mx-auto px-4 py-12">
        {showUpload ? (
          <div className="space-y-6">
            <div className="text-center mb-8">
              <h1 className="text-4xl font-bold text-slate-100 mb-3">
                Quantum-Morph Visualizer
              </h1>
              <p className="text-slate-400">
                Scientific visualization for AI-generated carbon capture materials
              </p>
            </div>

            <FileUpload onDataLoaded={handleDataLoaded} />

            <div className="flex justify-center">
              <button
                onClick={handleUseSample}
                className="bg-slate-800 hover:bg-slate-700 text-slate-300 px-6 py-3 rounded-lg border border-slate-600 transition-colors"
              >
                Load Sample Data
              </button>
            </div>
          </div>
        ) : data ? (
          <div className="space-y-8">
            <div className="flex justify-between items-center">
              <div>
                <h1 className="text-2xl font-bold text-slate-100">
                  Material Analysis Report
                </h1>
                <p className="text-slate-400 text-sm">AI-Optimized Carbon Capture Design</p>
              </div>
              <button
                onClick={handleReset}
                className="bg-slate-800 hover:bg-slate-700 text-slate-300 px-4 py-2 rounded-lg border border-slate-600 transition-colors text-sm"
              >
                Load Different Data
              </button>
            </div>

            <Overview
              confidence={data.overview.confidence}
              structuralRegime={data.overview.structuralRegime}
            />

            <MaterialInput data={data.materialInput} />

            <ProcessPipeline data={data.processPipeline} />

            <CompositeFormation data={data.compositeFormation} />

            <Performance data={data.performance} />

            <RiskAssessment data={data.riskAssessment} />

            <ScientificInterpretation interpretation={data.interpretation} />

            <div className="text-center pt-8 pb-4">
              <p className="text-slate-500 text-sm">
                Generated by Quantum-Morph AI Engine • For Research and Educational Purposes
              </p>
            </div>
          </div>
        ) : null}
      </div>
    </div>
  );
}

export default App;
